### ISSUE TITLE
suggestion, use: ~= for case insensitive compare

### ISSUE THREAD

**Issue by dominictarr** [DamonOehlman/matchme#1]
~= would be more elegant than a `{caseInsensitive: true}` option. 
It would also mean that the expression string contains everything needed to execute the expression.

on eval: this is the sort thing that eval is rightly used for.
eval is a problem when people use it when they could have just used a closure.
I mean, you could remove write an evaluator to execute the expression,
but that is basically what eval does.

The problem with discouraging use of eval by calling it "evil" is that no one learns _why_ it's bad.

**Comment by DamonOehlman** [comment]
Thanks Dominic,

Good suggestion - I'll have a look at implementing that.  

With regards to the eval comment, I should probably express this more clearly in the README.  Definitely agree that the historical blanket **don't use eval** is over the top.

Cheers,
Damon.

**Comment by DamonOehlman** [comment]
From `matchme@2` a `=~` as a case insensitive match.
